# Generated by Django 5.1.15 on 2026-08-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='dms_adapter_type',
            field=models.CharField(default='mock', help_text="Adapter identifier, e.g. 'mock', 'autologica', 'custom'.", max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dms_config',
            field=models.JSONField(blank=True, default=dict, help_text='Adapter-specific configuration (connection string, credentials, etc.).'),
        ),
    ]
