# Generated by Django 5.1.15 on 2026-08-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('core', '0002_tenant_dms_adapter_type_tenant_dms_config'),
    ]

    operations = [
    ]
