# Generated by Django 5.1.15 on 2026-08-14 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0002_part_special_flags_classificationresult'),
        ('core', '0003_merge_20260813_0503'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('handled', 'Handled'), ('ordered', 'Ordered')], default='pending', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(default='external_supplier', help_text='Placeholder for WU-10 source resolution (transfer/supplier).', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('punto_pedido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planning_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('explanation', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('velocity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='branches.branch')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_recommendations', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.part')),
                ('source_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_for_recommendations', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'branch', 'state'], name='recommendat_tenant__79dd3e_idx'), models.Index(fields=['state'], name='recommendat_state_7341cf_idx'), models.Index(fields=['created_at'], name='recommendat_created_0cbb1c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('tenant', 'branch', 'part'), name='unique_pending_recommendation_per_part')],
            },
        ),
    ]
