# Generated by Django 5.1.15 on 2026-08-14 13:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_partial',
            field=models.BooleanField(default=False, help_text='True when internal sources cannot cover the full recommended quantity.'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='partial_gap',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Quantity still needed after allocating all available internal excess stock.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='source_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='Multi-source allocation: list of {source_type, source_branch, quantity}.'),
        ),
    ]
