# Generated by Django 5.1.15 on 2026-08-14 13:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_recommendation_is_partial_recommendation_partial_gap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, help_text='Default approver (branch manager); escalation may reassign in WU-12.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='run_date',
            field=models.DateField(db_index=True, default=datetime.date.today, help_text='Run date used for idempotency and rejection reopening rules.'),
        ),
    ]
