# Generated by Django 5.1.15 on 2026-08-14 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendation_assigned_approver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When the recommendation was last escalated.', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='User who manually escalated the recommendation (system escalations leave this null).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='escalation_level',
            field=models.CharField(choices=[('none', 'None'), ('coordinator', 'Coordinator'), ('gerente', 'Gerente')], default='none', help_text='Current escalation level for this recommendation.', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Why this recommendation was escalated (threshold crossed, etc.).'),
        ),
    ]
