# Generated by Django 5.1.15 on 2026-08-13 05:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0003_merge_20260813_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEnTransito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expected_arrival', models.DateField()),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Recommendation ID or other external reference that initiated the transfer.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='branches.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transit_records', to='catalog.part')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['expected_arrival', 'destination_branch', 'part'],
                'indexes': [models.Index(fields=['tenant', 'destination_branch', 'status'], name='inventory_s_tenant__138717_idx'), models.Index(fields=['tenant', 'source_branch', 'status'], name='inventory_s_tenant__868ba0_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_disponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('stock_en_transito', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='branches.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.part')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['branch', 'part__internal_sku_code'],
                'indexes': [models.Index(fields=['tenant', 'branch', 'part'], name='inventory_s_tenant__665688_idx'), models.Index(fields=['last_synced_at'], name='inventory_s_last_sy_ed2ab8_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'part'), name='unique_stock_per_tenant_branch_part')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Adjustment'), ('return', 'Return')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_date', models.DateField()),
                ('source', models.CharField(default='dms', max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='branches.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.part')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-movement_date', 'branch', 'part'],
                'indexes': [models.Index(fields=['tenant', 'branch', 'part', 'movement_date'], name='inventory_s_tenant__4e6677_idx'), models.Index(fields=['movement_date'], name='inventory_s_movemen_25c7cf_idx')],
            },
        ),
    ]
