# Generated by Django 5.1.15 on 2026-08-18 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_auditlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('dms_connecting', 'DMS connecting'), ('dms_connected', 'DMS connected'), ('sales_backfilling', 'Sales backfilling'), ('backfill_complete', 'Backfill complete'), ('manager_assigning', 'Manager assigning'), ('test_running', 'Test run in progress'), ('live', 'Live'), ('failed', 'Failed')], default='not_started', max_length=30)),
                ('dms_adapter_type', models.CharField(blank=True, max_length=50)),
                ('dms_config', models.JSONField(blank=True, default=dict)),
                ('dms_connected_at', models.DateTimeField(blank=True, null=True)),
                ('dms_test_status', models.CharField(blank=True, max_length=20)),
                ('sales_backfilled_until', models.DateField(blank=True, null=True)),
                ('sales_backfill_count', models.IntegerField(default=0)),
                ('manager_assigned', models.BooleanField(default=False)),
                ('test_run_completed_at', models.DateTimeField(blank=True, null=True)),
                ('test_run_recommendations_count', models.IntegerField(default=0)),
                ('go_live_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='onboarding__tenant__054fa8_idx')],
            },
        ),
    ]
