# Generated by Django 5.1.15 on 2026-08-18 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('core', '0005_alter_auditlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('replenishment', 'Replenishment'), ('classification', 'Classification')], max_length=20)),
                ('run_date', models.CharField(max_length=20)),
                ('recommendations_count', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_runs', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_runs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'run_type', 'run_date'], name='scheduling__tenant__385754_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'run_type', 'run_date', 'branch'), name='unique_scheduled_run')],
            },
        ),
    ]
