# Generated by Django 5.1.15 on 2026-08-13 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenant_dms_adapter_type_tenant_dms_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_sku_code', models.CharField(max_length=100)),
                ('primary_manufacturer_code', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(default='PCS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant', 'internal_sku_code'],
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_target_code', models.CharField(blank=True, help_text='External code used when the target part is in another system.', max_length=100)),
                ('type', models.CharField(choices=[('alternative_manufacturer', 'Alternative Manufacturer'), ('same_part_alternative_code', 'Same Part Alternative Code'), ('successor', 'Successor'), ('predecessor', 'Predecessor'), ('substitutable', 'Substitutable')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('source_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_cross_references', to='catalog.part')),
                ('target_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_cross_references', to='catalog.part')),
            ],
            options={
                'ordering': ['tenant', 'source_part', 'type'],
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['tenant', 'primary_manufacturer_code'], name='catalog_par_tenant__254753_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['tenant', 'category'], name='catalog_par_tenant__0111b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('tenant', 'internal_sku_code'), name='unique_sku_per_tenant'),
        ),
    ]
