# Generated by Django 5.1.15 on 2026-08-14 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0003_merge_20260813_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='special_flags',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"is_campaign": false, "is_non_stock": false, "campaign_notes": ""}'),
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume_class', models.CharField(blank=True, help_text='VC1..VC8 or empty for cold-start.', max_length=4)),
                ('lifecycle_stage', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('pre_obsolete', 'Pre-Obsolete'), ('obsolete', 'Obsolete'), ('inactive', 'Inactive'), ('special_campaign', 'Special (Campaign)'), ('special_non_stock', 'Special (Non-Stock)')], max_length=30)),
                ('lifecycle_subcode', models.CharField(blank=True, help_text='Granular code: N1/N2/N3 for new parts, OBS-P/OBS-R/etc. when applicable.', max_length=10)),
                ('annual_sales', models.PositiveIntegerField(default=0)),
                ('days_since_last_sale', models.PositiveIntegerField(blank=True, null=True)),
                ('months_since_first_seen', models.PositiveIntegerField(blank=True, null=True)),
                ('classified_at', models.DateTimeField()),
                ('classifier_version', models.CharField(default='1.0', max_length=10)),
                ('special_flags', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='branches.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='catalog.part')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-classified_at'],
                'indexes': [models.Index(fields=['tenant', 'part', 'branch'], name='catalog_cla_tenant__f83170_idx'), models.Index(fields=['lifecycle_stage'], name='catalog_cla_lifecyc_3f2b98_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'part', 'branch', 'classifier_version'), name='unique_classification_per_version')],
            },
        ),
    ]
