# Generated by Django 5.1.15 on 2026-08-14 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0002_part_special_flags_classificationresult'),
        ('core', '0004_auditlog_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('override_type', models.CharField(choices=[('persistent', 'Persistent'), ('per_run', 'Per-Run'), ('with_expiry', 'With-Expiry')], max_length=20)),
                ('override_value', models.DecimalField(decimal_places=4, help_text='Velocity or demand value to use instead of the calculated value.', max_digits=12)),
                ('expires_at', models.DateField(blank=True, help_text='Required for WITH_EXPIRY overrides.', null=True)),
                ('run_id', models.CharField(blank=True, help_text='Required for PER_RUN overrides: the replenishment run this applies to.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Null means the override applies tenant-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_overrides', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_overrides', to='catalog.part')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'part', 'branch'], name='catalog_dem_tenant__417c7f_idx'), models.Index(fields=['expires_at'], name='catalog_dem_expires_24d880_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('override_type', 'persistent')), fields=('tenant', 'part', 'branch', 'override_type'), name='unique_persistent_demand_override')],
            },
        ),
    ]
