# Generated by Django 5.1.15 on 2026-08-13 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenant_dms_adapter_type_tenant_dms_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique within the tenant, e.g. SUC-001 or CD-001', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('sucursal', 'Sucursal'), ('centro_distribucion', 'Centro de Distribución')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_branches', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('parent_branch', models.ForeignKey(blank=True, help_text='For sucursales: the DC that supplies them. For DCs: null (top-level in v1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_branches', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_branch_code_per_tenant')],
            },
        ),
    ]
