# Generated by Django 5.1.15 on 2026-08-17 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_auditlog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new_recommendation', 'New recommendation'), ('recommendation_escalated', 'Recommendation escalated'), ('recommendation_approved', 'Recommendation approved'), ('recommendation_rejected', 'Recommendation rejected'), ('partial_fulfillment', 'Partial fulfillment detected'), ('cross_coordinator_pending', 'Cross-coordinator transfer pending'), ('override_created', 'Demand override created'), ('override_expired', 'Demand override expired')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'), models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__b302ab_idx')],
            },
        ),
    ]
